name: petitparser
version: 1.1.3
author: Lukas Renggli <renggli@gmail.com>
description: Dynamic parser combinator framework.
homepage: https://github.com/renggli/PetitParserDart
environment:
  sdk: '>=1.0.0 <2.0.0'
documentation: http://jenkins.lukas-renggli.ch/job/PetitParserDart/javadoc
dev_dependencies:
  browser: '>=0.9.0 <0.11.0'
  junitconfiguration: '>=1.0.0 <2.0.0'
  matcher: '>=0.9.0 <0.11.0'
  unittest: '>=0.9.0 <0.12.0'
