name: petitparser
version: 0.2.4+m4
author: Lukas Renggli <renggli@gmail.com>
description: Dynamic parser combinator framework.
homepage: https://github.com/renggli/PetitParserDart
dev_dependencies:
  junitconfiguration: any
  unittest: '>=0.4.0'
  browser: '>=0.4.0'
