name: petitparser
version: 6.1.0

homepage: https://petitparser.github.io
repository: https://github.com/petitparser/dart-petitparser
description: A dynamic parser framework to build efficient grammars and parsers quickly.
screenshots:
  - description: 'PetitParser'
    path: petitparser.png
topics:
  - grammar
  - parser
  - parser-combinator
  - parsing
  - peg

environment:
  sdk: ^3.5.0
dependencies:
  meta: ^1.16.0
  collection: ^1.19.0
dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.0
