name: petitparser
version: 1.7.4
author: Lukas Renggli <renggli@gmail.com>
description: Parser framework that combines ideas from scannnerless
  parsing, parser combinators, parsing expression grammars and packrat
  parsers to model complex grammars and parsers as objects that can be
  reconfigured dynamically.
homepage: https://github.com/petitparser/dart-petitparser
environment:
  sdk: ">=1.20.0 <2.0.0"
dependencies:
  matcher: ^0.12.0
dev_dependencies:
  browser: ^0.10.0
  test: ^0.12.0
