name: petitparser
version: 1.5.1
author: Lukas Renggli <renggli@gmail.com>
description: Dynamic parser combinator framework.
homepage: https://github.com/renggli/dart-petitparser
environment:
  sdk: '>=1.8.0 <2.0.0'
dev_dependencies:
  browser: '>=0.10.0 <0.11.0'
  test: '>=0.12.1 <0.13.0'
