name: petitparser
version: 2.0.1

author: Lukas Renggli <renggli@gmail.com>
homepage: https://github.com/petitparser/dart-petitparser
description: A dynamic parser framework to build efficient grammars and parsers
  quickly.

environment:
  sdk: '>=2.0.0 <3.0.0'
dev_dependencies:
  test: ^1.3.0
