name: petitparser
version: 4.1.0

homepage: https://github.com/petitparser/dart-petitparser
description: A dynamic parser framework to build efficient grammars and parsers
  quickly.

environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  meta: ^1.3.0
dev_dependencies:
  test: ^1.17.0
