name: petitparser_examples
version: 3.1.0

homepage: https://github.com/petitparser/dart-petitparser
description: A collection of example parsers, applications, and benchmarks that
  illustrate the PetitParser framework.

environment:
  sdk: '>=2.7.0 <3.0.0'
dependencies:
  collection: ^1.14.0
  meta: ^1.2.0
  more: ^2.7.0
  petitparser: ^3.1.0
dependency_overrides:
  petitparser:
    path: ../petitparser
dev_dependencies:
  test: ^1.15.0
  build_runner: ^1.10.0
  build_web_compilers: ^2.11.0
