name: petitparser_examples
version: 4.1.0

homepage: https://github.com/petitparser/dart-petitparser
description: A collection of example parsers, applications, and benchmarks that
  illustrate the PetitParser framework.

environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  collection: ^1.15.0
  meta: ^1.3.0
  more: ^3.0.0
  petitparser: ^4.1.0
dependency_overrides:
  petitparser:
    path: ../petitparser
dev_dependencies:
  build_runner: ^1.12.0
  build_web_compilers: ^2.16.0
  test: ^1.16.0
